name: Lint & Build

on:
  push:
    branches:
      - main

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Oculus OpenXR SDK (private)
        uses: actions/checkout@v2
        with:
          repository: zigen-project/oculus-openxr-mobile-sdk
          ssh-key: ${{ secrets.DEPLOY_KEY_OCULUS_OPENXR_MOBILE_SDK }}
          path: ovr_openxr_mobile_sdk

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: ClangFormat Check
        run: find . -regex "^\.\/app/src/main/cpp/.*\.\(h\|cpp\)" | xargs clang-format --dry-run -Werror

      - name: Gradle build
        run: ./gradlew build

      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: results
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml
          if-no-files-found: error
          retention-days: 14
